[FEAT] Replace Gatsby icons
process-analytics/process-analytics.dev pull request #10
Opened 2021-06-17 14:27 UTC by csouchet

Depends on #9

2021-06-18 14:15 UTC, tbouffard requested changes
We have decided to remove the public folder from the repository as it only contains generated content. See https://github.com/process-analytics/process-analytics.dev/pull/9#discussion_r654224742
This is still a work in progress

2021-06-18 15:00 UTC, tbouffard approved these changes
I am not sure we need both the favicon and the logo files

2021-06-18 15:03 UTC, csouchet commented
> I am not sure we need both the favicon and the logo files

I'm not sure too, but I don't now how Gatsby generates all the icon. It generates some icons bigger than the original (the quality is bad). So, maybe we can change that later, when we have a bigger original icon.

2021-06-18 15:05 UTC, csouchet commented on README.md
> +        <a href="CODE_OF_CONDUCT.md">
I badly merge the conflicts.
I didn't see in a previous PR that I remove the logo 😞

2021-06-18 15:17 UTC, tbouffard commented
about the logo, we have it in svg so we can create png, ico, ... files at any resolution.
[Process-Analytics-logo_svg.zip](https://github.com/process-analytics/process-analytics.dev/files/6677905/Process-Analytics-logo_svg.zip)

2021-06-18 15:37 UTC, csouchet commented
I did some tests with SVG image, it didn't work. I don't know why.
I try again why only SVG logo & removing the other images. And it works ^^

The plugin who generates the icons: https://www.gatsbyjs.com/plugins/gatsby-plugin-manifest/

2021-06-21 09:11 UTC, tbouffard commented
ok let's start with the single svg logo

2021-06-21 09:11 UTC, merged